PACKAGE_NAME=make
PACKAGE_VERSION=$MAKE_VERSION
BUNDLE_ID=com.modern-ppc.make
TITLE='GNU Make 4.4.1'
DESCRIPTION='Current GNU Make for building modern source trees on Tiger.'
REQUIRED=false
CHOICE_SELECTED=true
CHOICE_ENABLED=true
CHOICE_VISIBLE=true
